[package]
name = "worldbox"
version = "0.0.1"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "thin"

[dependencies.bevy]
version = "0.15.*"
default-features = false
features = [
    "bevy_pbr",
    "tonemapping_luts",
    "bevy_core_pipeline",
    "bevy_text",
    "bevy_ui",
    "bevy_state",
    "bevy_color",
    "bevy_asset",
    "bevy_sprite",
    "bevy_render",
    "bevy_window",
    "png",
    "multi_threaded",
    "file_watcher",
    "default_font",
    "x11"
]

[dependencies]
strum = {version="*", features=["derive"]}
serde = "1.0.*"
serde_yaml = "*"
rand = "0.8.*"
glob = "0.3.*"
ordermap = { version="0.5.*", features=["serde"]}
bevy_egui = "0.32.*"
rmp-serde = "*"
async-fs = "*"